apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aivyx-engine.fullname" . }}
  labels:
    {{- include "aivyx-engine.labels" . | nindent 4 }}
data:
  aivyx.toml: |
    {{- .Values.config | nindent 4 }}
